[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino

; Target 8MB flash partitions to leave room for M5Launcher and standard app space
board_build.partitions = default_8MB.csv

; Necessary for serial monitor over USB CDC on StampS3
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    m5stack/M5Unified@^0.2.9
    https://github.com/m5stack/M5Cardputer.git#1.2.0
    bblanchon/ArduinoJson@^7.0.4
    links2004/WebSockets@^2.4.1

extra_scripts = 
    pre:git_version.py
    post:merge_firmware.py

