#include "HelpView.h"

namespace {

// Lines are at most 38 characters: the screen fits 40 at text size 1.
const TextPageLine LINES[] = {
    {"Anywhere", 0},
    {" TAB          Next tab", 1},
    {" GO (top)     Enter, or jump to", 1},
    {"              Chat if enabled", 2},
    {" Hold ESC     Sleep, if enabled", 1},
    {" GO           Always wakes it", 1},
    {"", 1},
    {"Lists (Home and Entities)", 0},
    {" Up / Down    Move", 1},
    {" ; and .      Move", 1},
    {" Left / Right Entities sub-tab", 1},
    {" , and /      Entities sub-tab", 1},
    {" Letters      Jump to a name", 1},
    {" ENTER        Open details", 1},
    {" SPACE        Toggle on/off *", 1},
    {"              Pauses/resumes media", 2},
    {" + and -      Brightness/volume *", 1},
    {" Ctrl-F       Add/remove favorite", 1},
    {" Ctrl-Up/Dn   Reorder a favorite", 1},
    {" * can be turned off in Settings", 2},
    {" Reordering works on the Entities", 2},
    {" > Favorites sub-tab, when the", 2},
    {" Favorites Sort setting is Order.", 2},
    {"", 1},
    {"Detail window", 0},
    {" BACKSPACE    Close", 1},
    {" ESC, ` or ~  Close", 1},
    {" TAB          Close, not next tab", 1},
    {" ENTER        Run the action", 1},
    {"", 1},
    {"Media player", 0},
    {" ENTER or P   Play / pause", 1},
    {" Up / Down    Volume", 1},
    {" + and -      Volume", 1},
    {" Left / Right Seek, hold to ramp", 1},
    {" M            Mute", 1},
    {" S            Stop", 1},
    {"", 1},
    {"Light", 0},
    {" ENTER        Toggle on/off", 1},
    {" Up / Down    Brightness", 1},
    {" + and -      Brightness", 1},
    {"", 1},
    {"Thermostat", 0},
    {" + and -      Target temperature", 1},
    {" ENTER        Cycle HVAC mode", 1},
    {"", 1},
    {"Chat", 0},
    {" Type, ENTER  Send", 1},
    {" BACKSPACE    Delete a character", 1},
    {" Hold GO      Speak a request", 1},
    {"", 1},
    {"Menu", 0},
    {" Up / Down    Move", 1},
    {" ENTER        Open a page", 1},
    {" BACKSPACE    Back to the menu", 1},
    {"", 1},
    {"Settings", 0},
    {" Left / Right Change a value", 1},
    {" + and -      Change a value", 1},
    {" Hold either  Repeat", 1},
    {" ENTER        Open a > row", 1},
    {" BACKSPACE    Back to Settings", 1},
    {"", 1},
    {"Connecting screens", 0},
    {" ESC twice    Forget the network", 1},
    {" H twice      Clear the HA setup", 1},
    {" On first setup, ESC just returns", 2},
    {" to the network list.", 2},
    {"", 1},
    {"Power levels", 0},
    {" Each timer in Settings hands off", 2},
    {" to the next level down:", 2},
    {" Dim T/O      Screen dims", 1},
    {" Disp Off T/O Screen sleeps, the", 1},
    {"              radio dozes", 2},
    {" Soft Sleep   Wi-Fi off, CPU slowed.", 1},
    {"              Still awake; a key", 2},
    {"              resumes it (or movement,", 2},
    {"              on a Cardputer ADV)", 2},
    {" Sleep T/O    Sleeps for real, at", 1},
    {"              the Sleep Depth setting", 2},
    {"", 1},
    {" Sleep Depth: OFF stops at Soft", 2},
    {" Sleep. LIGHT resumes where it", 2},
    {" left off. DEEP draws least but", 2},
    {" reboots and reconnects on wake.", 2},
    {" Wake On GO Only limits the wake", 2},
    {" key; GO always works.", 2},
    {" Hold ESC sleeps at once, if", 2},
    {" ESC for Sleep is on. A progress", 2},
    {" bar shows when to let go.", 2},
};

constexpr int LINE_COUNT = sizeof(LINES) / sizeof(LINES[0]);

}  // namespace

HelpView::HelpView(ConfigManager& config) : TextPageView(config, LINES, LINE_COUNT) {}
