#include "HelpView.h"

namespace {

// Lines are at most 38 characters: the screen fits 40 at text size 1.
const TextPageLine LINES[] = {
    {"Anywhere", 0},
    {" TAB          Next tab", 1},
    {" GO (top)     Enter, or jump to", 1},
    {"              Chat if enabled", 2},
    {" Hold ESC     Sleep, if enabled", 1},
    {"", 1},
    {"Lists (Home and Entities)", 0},
    {" Up / Down    Move", 1},
    {" ; and .      Move", 1},
    {" Left / Right Entities sub-tab", 1},
    {" , and /      Entities sub-tab", 1},
    {" Letters      Jump to a name", 1},
    {" ENTER        Open details", 1},
    {" SPACE        Toggle on/off *", 1},
    {" + and -      Brightness/volume *", 1},
    {" Ctrl-F       Add/remove favorite", 1},
    {" * can be turned off in Settings", 2},
    {"", 1},
    {"Detail window", 0},
    {" BACKSPACE    Close", 1},
    {" ESC, ` or ~  Close", 1},
    {" TAB          Close, not next tab", 1},
    {" ENTER        Run the action", 1},
    {"", 1},
    {"Media player", 0},
    {" ENTER or P   Play / pause", 1},
    {" Up / Down    Volume", 1},
    {" + and -      Volume", 1},
    {" Left / Right Seek, hold to ramp", 1},
    {" M            Mute", 1},
    {" S            Stop", 1},
    {"", 1},
    {"Thermostat", 0},
    {" + and -      Target temperature", 1},
    {" ENTER        Cycle HVAC mode", 1},
    {"", 1},
    {"Chat", 0},
    {" Type, ENTER  Send", 1},
    {" BACKSPACE    Delete a character", 1},
    {" Hold GO      Speak a request", 1},
    {"", 1},
    {"Menu", 0},
    {" Up / Down    Move", 1},
    {" ENTER        Open a page", 1},
    {" BACKSPACE    Back to the menu", 1},
    {"", 1},
    {"Settings", 0},
    {" Left / Right Change a value", 1},
    {" + and -      Change a value", 1},
    {" Hold either  Repeat", 1},
    {"", 1},
    {"Connecting screens", 0},
    {" ESC twice    Forget the network", 1},
    {" H twice      Clear the HA setup", 1},
    {" On first setup, ESC just returns", 2},
    {" to the network list.", 2},
    {"", 1},
    {"Note", 0},
    {" W and S do not scroll lists.", 2},
    {" They type-ahead like any other", 2},
    {" letter. Use the arrow keys, or", 2},
    {" the ; and . keys.", 2},
};

constexpr int LINE_COUNT = sizeof(LINES) / sizeof(LINES[0]);

}  // namespace

HelpView::HelpView(ConfigManager& config) : TextPageView(config, LINES, LINE_COUNT) {}
